[package]
name = "fastpay_core"
version = "0.1.0"
authors = ["Libra <oncall+libra@xmail.facebook.com>"]
publish = false
edition = "2018"

[dependencies]
bcs = "0.1.3"
bincode = "1.3.3"
coconut = { version = "0.1.0", path = "../coconut", features = ["with_serde"] }
failure = "0.1.8"
ff = "0.11.0"
futures = "0.3.17"
generic-array = { version = "0.14.4", features = ["serde"] }
hex = "0.4.3"
rand = "0.7.3"
serde = { version = "1.0.130", features = ["derive"] }
tokio = { version = "1.12.0", features = ["full"] }
ed25519 = "1.2.0"
ed25519-dalek = { version = "1.0.1", features = ["batch", "serde"] }
serde_json = "1.0.68"
serde-name = "0.2.0"
sha2 = "0.9.8"
structopt = "0.3.23"

[dev-dependencies]
similar-asserts = "1.1.0"
serde-reflection = "0.3.5"
serde_yaml = "0.8.21"
coconut = { version = "0.1.0", path = "../coconut", features = ["with_equality"] }
bulletproofs = { version = "0.1.0", path = "../bulletproofs", features = ["with_equality"] }
merlin = "2"
ff = "0.11.0"

[dependencies.bls12_381]
version = "0.6.0"
git = "https://github.com/matbd/bls12_381"
branch = "serde"
features = ["experimental"]

[[example]]
name = "generate-format"
path = "src/generate_format.rs"
test = false

