name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        rustup toolchain install 1.54.0-x86_64-unknown-linux-gnu
        rustup component add rustfmt --toolchain 1.54.0-x86_64-unknown-linux-gnu
        rustup component add clippy --toolchain 1.54.0-x86_64-unknown-linux-gnu
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Rustfmt
      run: cargo fmt -- --check
    - name: Clippy
      run: cargo clippy --all-targets
