name: Rust

on:
  push:
    branches: [ main, extensions ]
  pull_request:
    branches: [ main, extensions ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup
      run: |
        rustup toolchain install 1.60.0-x86_64-unknown-linux-gnu
        rustup component add rustfmt --toolchain 1.60.0-x86_64-unknown-linux-gnu
        rustup component add clippy --toolchain 1.60.0-x86_64-unknown-linux-gnu
    - name: Build
      run: cargo build --all-features --verbose
    - name: Run tests (default features)
      run: cargo test --verbose
    - name: Clippy (all features)
      run: cargo clippy --all-features --all-targets
    - name: Clippy (default features)
      run: cargo clippy --all-targets
    - name: Rustfmt
      run: cargo fmt -- --check
